"""init

Revision ID: 023179c59903
Revises: 
Create Date: 2026-01-22 10:23:15.562154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023179c59903'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('require_area', sa.Boolean(), nullable=False),
    sa.Column('require_shift', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_token'), ['token'], unique=True)

    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('shift', sa.String(length=16), nullable=True),
    sa.Column('wants_followup', sa.Boolean(), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('employee_no', sa.String(length=50), nullable=True),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index('ix_responses_campaign_date', ['campaign_id', 'submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_submitted_at'), ['submitted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_responses_campaign_id'))
        batch_op.drop_index('ix_responses_campaign_date')

    op.drop_table('responses')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_token'))

    op.drop_table('campaigns')
    op.drop_table('surveys')
    op.drop_table('areas')
    # ### end Alembic commands ###
